### ISSUE TITLE
create release for Milestone 2

### ISSUE THREAD

**Issue by karlie-tr** [karlie-tr/dsci-310-group-03#44]
- [x] #58 
- [x] In mounted Docker container: rerun notebook with abstracted function using README.md instructions
- [x] delete merged branches; close finished issues 
- [x] Submit link to canvas
